window.EMOSEED_GIFT_EVENTS=[
{id:'new-year',title:'새해',type:'seasonal',month:1,day:1,recipient:'가족·동료·나 자신',meaning:'새로운 시작을 응원하기 좋은 날',flowers:['튤립','프리지어','수선화'],message:'새해의 시작이 환하고 다정하게 피어나길 바라요.',leadDays:3},
{id:'graduation',title:'졸업 시즌',type:'seasonal',month:2,day:1,recipient:'졸업생·후배·친구',meaning:'2월 한 달 동안 졸업과 새로운 출발을 축하하기 좋은 시기',flowers:['프리지어','거베라','해바라기'],message:'지금까지 정말 수고했어요. 새로운 시작도 마음껏 응원할게요.',leadDays:7,highDemand:true},
{id:'valentine',title:'밸런타인데이',type:'popular',month:2,day:14,recipient:'연인·좋아하는 사람',meaning:'사랑과 호감을 표현하는 대중문화 기념일',flowers:['장미','튤립','라넌큘러스'],message:'좋아하는 마음을 오늘은 조금 더 솔직하게 전하고 싶어요.',leadDays:7,highDemand:true},
{id:'womens-day',title:'세계 여성의 날',type:'global',month:3,day:8,recipient:'소중한 여성·동료·가족',meaning:'여성의 권리와 성취를 기리는 국제 기념일',flowers:['노란 튤립','프리지어','거베라'],message:'당신의 삶과 선택, 그리고 매일의 용기를 응원해요.',leadDays:3},
{id:'white-day',title:'화이트데이',type:'popular',month:3,day:14,recipient:'연인·좋아하는 사람',meaning:'마음을 답하고 표현하는 대중문화 기념일',flowers:['흰 튤립','리시안셔스','안개꽃'],message:'전하고 싶었던 마음을 오늘은 꽃과 함께 건넬게요.',leadDays:5},
{id:'arbor-day',title:'식목일',type:'official',month:4,day:5,recipient:'가족·친구·나 자신',meaning:'나무를 심고 자연의 소중함을 생각하는 법정 기념일',flowers:['화분 식물','허브','작은 관엽식물'],message:'우리의 하루에도 오래 자랄 초록 하나를 심어봐요.',leadDays:3},
{id:'earth-day',title:'지구의 날',type:'global',month:4,day:22,recipient:'친구·동료·나 자신',meaning:'환경을 생각하며 오래 키울 수 있는 식물을 선물하기 좋은 날',flowers:['허브 화분','다육식물','작은 관엽식물'],message:'오늘의 작은 초록이 오래 이어지는 변화를 만들길 바라요.',leadDays:3},
{id:'childrens-day',title:'어린이날',type:'official',month:5,day:5,recipient:'어린이·조카·가족',meaning:'아이의 취향과 안전을 고려한 작은 꽃이나 식물 선물이 잘 어울리는 날',flowers:['거베라','해바라기','데이지'],message:'네가 좋아하는 것들을 마음껏 발견하며 자라길 응원해!',leadDays:4,highDemand:true},
{id:'parents-day',title:'어버이날',type:'official',month:5,day:8,recipient:'부모님·조부모님',meaning:'부모님의 사랑과 헌신에 감사하는 법정 기념일',flowers:['카네이션','리시안셔스','장미'],message:'늘 든든하게 곁을 지켜주셔서 감사합니다. 오래오래 건강하세요.',leadDays:10,highDemand:true},
{id:'mothers-day',title:'어머니의 날',type:'global',rule:'second-sunday-may',recipient:'어머니·보호자',meaning:'여러 나라에서 어머니와 돌봄의 가치를 기리는 날',flowers:['카네이션','작약','리시안셔스'],message:'당신의 다정함 덕분에 지금의 제가 있어요. 진심으로 감사해요.',leadDays:7,highDemand:true},
{id:'rose-day',title:'로즈데이',type:'popular',month:5,day:14,recipient:'연인·친구',meaning:'장미를 주고받는 대중문화 기념일',flowers:['장미','미니장미','리시안셔스'],message:'오늘 당신에게 가장 잘 어울리는 장미를 골랐어요.',leadDays:4},
{id:'teachers-day',title:'스승의 날',type:'official',month:5,day:15,recipient:'선생님·멘토',meaning:'스승의 은혜와 교육의 가치를 되새기는 법정 기념일',flowers:['카네이션','리시안셔스','거베라'],message:'가르쳐주신 마음과 시간, 오래 기억하겠습니다. 감사합니다.',leadDays:7,highDemand:true},
{id:'family-day',title:'세계 가정의 날',type:'global',month:5,day:15,recipient:'가족',meaning:'가족의 의미와 역할을 생각하는 유엔 국제 기념일',flowers:['장미','카네이션','해바라기'],message:'함께라서 평범한 하루도 특별해져요. 늘 고마워요.',leadDays:3},
{id:'coming-of-age',title:'성년의 날',type:'official',rule:'third-monday-may',recipient:'성년이 된 가족·친구·연인',meaning:'성년이 된 청년의 책임과 자부심을 축하하는 법정 기념일',flowers:['장미','튤립','프리지어'],message:'새로운 계절을 맞은 당신의 선택과 앞날을 응원해요.',leadDays:5},
{id:'environment-day',title:'세계 환경의 날',type:'global',month:6,day:5,recipient:'친구·동료·나 자신',meaning:'꽃다발보다 오래 키울 수 있는 식물이나 친환경 포장을 선택하기 좋은 날',flowers:['허브 화분','관엽식물','야생화 화분'],message:'우리의 작은 선택이 더 푸른 내일로 이어지길 바라요.',leadDays:3},
{id:'fathers-day',title:'아버지의 날',type:'global',rule:'third-sunday-june',recipient:'아버지·보호자',meaning:'여러 나라에서 아버지와 돌봄의 가치를 기리는 날',flowers:['해바라기','거베라','난초'],message:'늘 말없이 든든한 힘이 되어주셔서 감사합니다.',leadDays:5},
{id:'friendship-day',title:'국제 우정의 날',type:'global',month:7,day:30,recipient:'친구·동료',meaning:'우정과 연대의 가치를 기리는 유엔 국제 기념일',flowers:['백일홍','거베라','해바라기'],message:'늘 내 편이 되어줘서 고마워. 우리 우정도 오래 피어나길!',leadDays:3},
{id:'youth-day',title:'국제 청년의 날',type:'global',month:8,day:12,recipient:'청년·후배·친구',meaning:'새로운 가능성과 도전을 응원하기 좋은 국제 기념일',flowers:['해바라기','프리지어','거베라'],message:'당신의 가능성과 선택이 더 멀리 피어나길 응원해요.',leadDays:3},
{id:'older-persons-day',title:'세계 노인의 날',type:'global',month:10,day:1,recipient:'조부모님·어르신',meaning:'노년의 존엄과 기여를 기리는 유엔 국제 기념일',flowers:['카네이션','국화','리시안셔스'],message:'오랜 시간 나눠주신 지혜와 사랑에 감사드립니다.',leadDays:4},
{id:'world-teachers-day',title:'세계 교사의 날',type:'global',month:10,day:5,recipient:'교사·멘토',meaning:'교육자들의 역할과 헌신을 기리는 국제 기념일',flowers:['거베라','카네이션','프리지어'],message:'누군가의 가능성을 믿어주시는 모든 순간에 감사드립니다.',leadDays:4},
{id:'mental-health-day',title:'세계 정신건강의 날',type:'global',month:10,day:10,recipient:'친구·가족·나 자신',meaning:'안부를 묻고 스스로를 돌보는 작은 꽃을 건네기 좋은 날',flowers:['라벤더','데이지','리시안셔스'],message:'괜찮지 않은 날에도 혼자가 아니라는 걸 기억해줘.',leadDays:2},
{id:'volunteer-day',title:'세계 자원봉사자의 날',type:'global',month:12,day:5,recipient:'봉사자·동료·단체',meaning:'누군가를 위해 시간을 내어준 사람에게 감사를 전하기 좋은 날',flowers:['거베라','프리지어','카네이션'],message:'당신이 나눈 시간과 마음이 많은 사람에게 따뜻함이 되었어요.',leadDays:3},
{id:'year-end',title:'연말 감사 시즌',type:'seasonal',month:12,day:1,recipient:'가족·친구·동료·고객',meaning:'한 해의 감사와 수고를 전하기 좋은 시기',flowers:['포인세티아','장미','목화와 그린 소재'],message:'올해 함께해주셔서 정말 고마웠어요. 따뜻한 연말 보내세요.',leadDays:5,highDemand:true},
{id:'christmas',title:'크리스마스',type:'seasonal',month:12,day:25,recipient:'가족·연인·친구',meaning:'사랑과 감사, 따뜻한 마음을 나누기 좋은 날',flowers:['빨간 장미','포인세티아','흰 리시안셔스'],message:'당신과 함께여서 올겨울이 더 따뜻해요. 메리 크리스마스!',leadDays:7,highDemand:true}
];

window.EMOSEED_BOUQUETS={
love:{title:'진심을 전하는 로맨틱 꽃다발',flowers:['장미','라넌큘러스','리시안셔스'],meaning:'사랑·매력·변치 않는 마음',messages:['좋아하는 마음을 오늘은 꽃과 함께 솔직하게 전할게요.','당신과 함께하는 평범한 날들이 제게는 가장 특별해요.','천천히 오래, 지금처럼 곁에 있고 싶어요.']},
birthday:{title:'밝은 에너지의 생일 꽃다발',flowers:['거베라','해바라기','튤립'],meaning:'기쁨·축하·밝은 시작',messages:['태어난 오늘을 진심으로 축하해요. 올해도 환하게 빛나길!','당신다운 행복이 가득한 한 해가 되길 바라요.','오늘의 주인공에게 가장 밝은 꽃을 보냅니다.']},
thanks:{title:'부드러운 감사 꽃다발',flowers:['리시안셔스','카네이션','프리지어'],meaning:'감사·존경·우정',messages:['말로 다 전하지 못한 고마움을 꽃에 담아 보냅니다.','늘 세심하게 마음 써주셔서 진심으로 감사해요.','당신 덕분에 많은 순간이 더 따뜻했습니다.']},
apology:{title:'진심을 담은 화해 꽃다발',flowers:['수국','흰 튤립','리시안셔스'],meaning:'진심·용서·새로운 시작',messages:['상처를 드려 미안해요. 변명보다 달라지는 모습으로 보여드릴게요.','제 마음을 솔직하게 전하지 못해 미안합니다.','서두르지 않고, 다시 신뢰를 쌓아가고 싶어요.']},
comfort:{title:'조용히 곁을 지키는 위로 꽃다발',flowers:['라벤더','데이지','리시안셔스'],meaning:'평온·희망·다정한 위로',messages:['무슨 말을 해야 할지 몰라도, 곁에 있다는 마음은 전하고 싶어요.','오늘은 애쓰지 않아도 괜찮아요. 천천히 쉬어가요.','혼자 견디지 않아도 돼요. 필요할 때 언제든 곁에 있을게요.']},
graduation:{title:'새로운 출발을 응원하는 꽃다발',flowers:['프리지어','거베라','해바라기'],meaning:'새 출발·희망·응원',messages:['지금까지 정말 수고했어요. 새로운 시작도 힘껏 응원할게요.','끝이 아니라 멋진 다음 장의 시작을 축하해요.','당신이 걸어갈 새로운 길에 좋은 일이 가득하길!']},
housewarming:{title:'공간을 밝혀주는 집들이 선물',flowers:['카라','극락조화','치자꽃'],meaning:'환영·도약·은은한 행복',messages:['새로운 공간에 편안하고 좋은 일만 가득하길 바라요.','이 집에서 행복한 추억이 차곡차곡 쌓이길!','새로운 보금자리를 진심으로 축하해요.']},
parents:{title:'존경과 감사를 담은 꽃다발',flowers:['카네이션','장미','리시안셔스'],meaning:'존경·사랑·감사',messages:['늘 든든한 사랑으로 지켜주셔서 감사합니다.','표현은 서툴지만 언제나 사랑하고 감사해요.','오래오래 건강하게 제 곁에 계셔주세요.']},
friendship:{title:'오래가는 우정 꽃다발',flowers:['백일홍','거베라','해바라기'],meaning:'우정·기쁨·밝은 마음',messages:['늘 내 편이 되어줘서 고마워. 우리 우정도 오래 피어나길!','함께 웃을 수 있는 친구가 있어서 참 다행이야.','앞으로도 서로의 좋은 날을 가장 먼저 축하해주자.']},
self:{title:'나를 위한 작은 정원 선물',flowers:['라넌큘러스','튤립','데이지'],meaning:'매력·새로운 시작·희망',messages:['오늘도 잘 버틴 나에게 작은 꽃을 선물합니다.','완벽하지 않아도 충분히 잘하고 있어.','내 마음을 가장 먼저 돌보는 하루가 되길.']},
anniversary:{title:'함께한 시간을 기념하는 꽃다발',flowers:['장미','작약','안개꽃'],meaning:'사랑·행복·변치 않는 마음',messages:['함께한 시간만큼 앞으로의 날들도 다정하게 채워가고 싶어요.','당신과 만든 모든 계절이 제게는 소중해요.','오늘도, 앞으로도 당신과 함께라서 행복해요.']},
promotion:{title:'새로운 성취를 축하하는 꽃다발',flowers:['거베라','극락조화','해바라기'],meaning:'성취·도약·밝은 미래',messages:['새로운 자리에서 더 멋지게 빛날 당신을 응원합니다.','그동안의 노력이 만든 결과를 진심으로 축하해요.','다음 도약도 당신답게 멋지게 해낼 거예요.']},
opening:{title:'성공과 번영을 기원하는 개업 선물',flowers:['난초','극락조화','해바라기'],meaning:'성공·번영·도약',messages:['새로운 시작을 축하드리며 번창을 기원합니다.','이 공간에 좋은 인연과 기회가 가득하길 바랍니다.','멋진 출발을 진심으로 축하드립니다.']},
retirement:{title:'수고와 새 출발을 담은 꽃다발',flowers:['리시안셔스','해바라기','프리지어'],meaning:'감사·존경·새 출발',messages:['오랜 시간의 헌신과 노고에 진심으로 감사드립니다.','새롭게 시작될 여유로운 날들을 응원합니다.','함께할 수 있어 영광이었고 오래 기억하겠습니다.']},
recovery:{title:'빠른 회복을 바라는 밝은 꽃다발',flowers:['거베라','해바라기','데이지'],meaning:'회복·희망·밝은 에너지',messages:['천천히 잘 회복해서 다시 환하게 웃는 날을 기다릴게요.','몸과 마음이 하루빨리 편안해지길 바랍니다.','무리하지 말고 충분히 쉬어요. 늘 응원하고 있어요.']},
performance:{title:'무대와 전시를 축하하는 꽃다발',flowers:['거베라','라넌큘러스','리시안셔스'],meaning:'찬사·매력·응원',messages:['멋진 무대와 작품을 진심으로 축하해요.','당신의 시간과 열정이 빛나는 순간을 함께할 수 있어 기뻐요.','오늘의 박수와 축하를 꽃에 담아 보냅니다.']}
};
