(() => {
  const p='https://www.aspca.org/pet-care/aspca-poison-control/toxic-and-non-toxic-plants/';
  const flowers=[
    {id:'rose',name:'장미',emoji:'🌹',colors:['red','pink','white','yellow'],meanings:['사랑','감사','존경','축하'],seasons:['spring','summer','autumn','winter'],occasions:['birthday','anniversary','confession','thanks','apology','parents'],price:'mid',scent:'보통',care:{water:'매일 수위를 확인하고 1~2일마다 깨끗한 물로 교체하세요.',cut:'줄기 끝을 1~2cm 사선으로 다시 잘라주세요.',place:'직사광선과 난방기 바람을 피해 서늘한 곳에 두세요.',life:'대체로 7~12일'},pet:{cat:'safe',dog:'safe',note:'ASPCA는 장미를 고양이와 강아지에게 비독성으로 분류합니다. 다만 가시와 농약, 꽃병 물은 주의하세요.',source:p+'rose'}},
    {id:'sunflower',name:'해바라기',emoji:'🌻',colors:['yellow','orange'],meanings:['응원','희망','행복','존경'],seasons:['summer','autumn'],occasions:['birthday','graduation','thanks','cheer','newstart'],price:'mid',scent:'약함',care:{water:'물을 많이 마시는 편이라 매일 수위를 확인하세요.',cut:'굵은 줄기 끝을 사선으로 자르고 물에 잠기는 잎은 제거하세요.',place:'밝지만 직사광선이 강하지 않은 서늘한 곳이 좋아요.',life:'대체로 6~10일'},pet:{cat:'safe',dog:'safe',note:'ASPCA는 해바라기를 고양이와 강아지에게 비독성으로 분류합니다.',source:p+'sunflower'}},
    {id:'tulip',name:'튤립',emoji:'🌷',colors:['red','pink','white','yellow','purple'],meanings:['사랑','고백','새로운 시작','행복'],seasons:['spring'],occasions:['birthday','anniversary','confession','newstart','graduation'],price:'mid',scent:'약함',care:{water:'얕고 깨끗한 물을 자주 교체하세요.',cut:'줄기 끝을 곧게 조금씩 잘라주세요.',place:'빛을 향해 휘므로 꽃병 방향을 가끔 돌려주세요.',life:'대체로 5~10일'},pet:{cat:'danger',dog:'danger',note:'튤립은 반려동물에게 유해할 수 있으며 특히 구근의 독성 성분 농도가 높습니다.',source:p+'tulip'}},
    {id:'carnation',name:'카네이션',emoji:'🌺',colors:['red','pink','white','yellow'],meanings:['감사','존경','사랑','축하'],seasons:['spring','summer','autumn','winter'],occasions:['parents','thanks','birthday','teacher','graduation'],price:'low',scent:'약함',care:{water:'2일마다 물을 갈고 꽃병을 씻어주세요.',cut:'마디 바로 아래를 피해 사선으로 잘라주세요.',place:'통풍이 잘되고 서늘한 장소가 좋아요.',life:'대체로 10~18일'},pet:{cat:'caution',dog:'caution',note:'섭취 시 가벼운 위장 증상이나 피부 자극을 유발할 수 있어 접근을 막는 편이 안전합니다.',source:p+'carnation'}},
    {id:'gerbera',name:'거베라',emoji:'🌼',colors:['red','pink','white','yellow','orange'],meanings:['행복','응원','감사','새로운 시작'],seasons:['spring','summer','autumn','winter'],occasions:['birthday','cheer','graduation','thanks','newstart'],price:'low',scent:'약함',care:{water:'줄기가 무를 수 있어 물을 얕게 받고 자주 교체하세요.',cut:'깨끗한 칼로 줄기 끝을 곧게 조금 잘라주세요.',place:'꽃목이 꺾이지 않도록 세로로 지지해 주세요.',life:'대체로 7~14일'},pet:{cat:'safe',dog:'safe',note:'거베라는 일반적으로 고양이와 강아지에게 비독성으로 분류됩니다.',source:p+'gerbera-daisy'}},
    {id:'freesia',name:'프리지아',emoji:'💛',colors:['yellow','white','pink','purple'],meanings:['우정','새로운 시작','응원','감사'],seasons:['spring'],occasions:['graduation','newstart','thanks','friendship','birthday'],price:'low',scent:'강함',care:{water:'깨끗한 물을 1~2일마다 교체하세요.',cut:'줄기 끝을 사선으로 조금 잘라주세요.',place:'향이 강할 수 있으니 환기가 되는 곳이 좋아요.',life:'대체로 7~12일'},pet:{cat:'safe',dog:'safe',note:'일반적으로 반려동물에게 비독성으로 알려져 있으나 섭취는 막아주세요.',source:p}},
    {id:'lisianthus',name:'리시안셔스',emoji:'🤍',colors:['white','pink','purple','green'],meanings:['감사','변치 않는 사랑','우아함','응원'],seasons:['spring','summer','autumn'],occasions:['birthday','anniversary','thanks','wedding','cheer'],price:'mid',scent:'약함',care:{water:'2일마다 물을 교체하고 물에 잠기는 잎은 제거하세요.',cut:'줄기 끝을 사선으로 잘라 흡수 면적을 넓혀주세요.',place:'강한 햇빛과 높은 온도를 피하세요.',life:'대체로 10~14일'},pet:{cat:'safe',dog:'safe',note:'일반적으로 고양이와 강아지에게 비독성으로 알려져 있습니다.',source:p}},
    {id:'orchid',name:'호접란',emoji:'🪻',colors:['white','pink','purple','yellow'],meanings:['존경','우아함','행복','축하'],seasons:['spring','summer','autumn','winter'],occasions:['opening','promotion','parents','thanks','birthday'],price:'high',scent:'약함',care:{water:'절화는 물을 깨끗하게 유지하고 화분은 뿌리가 마른 뒤 물을 주세요.',cut:'절화 줄기 끝을 깨끗하게 사선으로 자르세요.',place:'직사광선 대신 밝은 간접광이 좋아요.',life:'절화 10~20일'},pet:{cat:'safe',dog:'safe',note:'대표적인 호접란은 일반적으로 고양이와 강아지에게 비독성으로 분류됩니다.',source:p}},
    {id:'lily',name:'참나리·백합속',emoji:'⚜️',colors:['white','pink','orange','yellow'],meanings:['순수','존경','축하','위로'],seasons:['spring','summer'],occasions:['wedding','thanks','memorial','birthday'],price:'mid',scent:'강함',care:{water:'물을 매일 확인하고 꽃가루가 떨어지기 전에 수술을 제거할 수 있어요.',cut:'줄기 끝을 사선으로 자르고 물에 잠기는 잎은 제거하세요.',place:'향이 강하므로 환기가 되는 곳에 두세요.',life:'대체로 7~14일'},pet:{cat:'danger',dog:'safe',note:'Lilium 속 백합은 고양이에게 매우 위험하며 꽃가루와 꽃병 물까지 노출을 피해야 합니다.',source:p+'lily'}},
    {id:'hydrangea',name:'수국',emoji:'🔵',colors:['blue','purple','pink','white','green'],meanings:['진심','감사','이해','변화'],seasons:['summer'],occasions:['birthday','thanks','apology','wedding','anniversary'],price:'mid',scent:'약함',care:{water:'물을 많이 마시므로 수위를 자주 확인하세요.',cut:'굵은 줄기 끝을 넓게 사선으로 자르고 잎을 최소화하세요.',place:'건조한 바람을 피하고 시원한 곳에 두세요.',life:'대체로 5~10일'},pet:{cat:'danger',dog:'danger',note:'수국은 섭취 시 반려동물에게 위장 증상 등을 유발할 수 있어 접근을 막아야 합니다.',source:p+'hydrangea'}},
    {id:'babybreath',name:'안개꽃',emoji:'☁️',colors:['white','pink'],meanings:['순수','영원한 사랑','감사','우정'],seasons:['spring','summer','autumn','winter'],occasions:['anniversary','wedding','birthday','thanks','friendship'],price:'low',scent:'약함',care:{water:'깨끗한 물을 얕게 유지하고 2일마다 교체하세요.',cut:'줄기 끝을 조금씩 다시 잘라주세요.',place:'습기가 지나치게 높지 않은 서늘한 곳이 좋아요.',life:'대체로 7~14일'},pet:{cat:'caution',dog:'caution',note:'섭취 시 가벼운 위장 증상을 일으킬 수 있어 접근을 막는 편이 안전합니다.',source:p+'babys-breath'}},
    {id:'chrysanthemum',name:'국화',emoji:'🏵️',colors:['yellow','white','purple','pink'],meanings:['성실','감사','평온','존경'],seasons:['autumn'],occasions:['thanks','parents','memorial','birthday'],price:'low',scent:'보통',care:{water:'잎이 물에 닿지 않게 정리하고 2일마다 물을 교체하세요.',cut:'줄기 끝을 사선으로 잘라주세요.',place:'서늘하고 통풍이 잘되는 곳에서 오래 갑니다.',life:'대체로 14~21일'},pet:{cat:'danger',dog:'danger',note:'국화는 고양이와 강아지에게 유해할 수 있어 섭취와 피부 접촉을 피해야 합니다.',source:p+'chrysanthemum'}},
    {id:'peony',name:'작약',emoji:'🌸',colors:['pink','white','red'],meanings:['행복','수줍음','사랑','축복'],seasons:['spring','summer'],occasions:['wedding','anniversary','birthday','confession'],price:'high',scent:'보통',care:{water:'충분한 깨끗한 물을 유지하고 매일 수위를 확인하세요.',cut:'굵은 줄기를 사선으로 잘라주세요.',place:'봉오리가 천천히 열리도록 서늘한 곳에 두세요.',life:'대체로 5~8일'},pet:{cat:'danger',dog:'danger',note:'작약은 섭취 시 반려동물에게 위장 증상을 유발할 수 있어 접근을 막아주세요.',source:p+'peony'}},
    {id:'ranunculus',name:'라넌큘러스',emoji:'🟠',colors:['pink','orange','yellow','white','red'],meanings:['매력','행복','찬란함','축하'],seasons:['spring'],occasions:['birthday','anniversary','confession','graduation'],price:'mid',scent:'약함',care:{water:'줄기가 무르기 쉬워 얕은 물을 자주 교체하세요.',cut:'줄기 끝을 조금씩 곧게 잘라주세요.',place:'꽃이 무거워지면 낮은 꽃병으로 지지해 주세요.',life:'대체로 7~12일'},pet:{cat:'danger',dog:'danger',note:'라넌큘러스류는 섭취 시 구강과 위장 자극을 유발할 수 있습니다.',source:p+'buttercup'}},
    {id:'daffodil',name:'수선화',emoji:'🌼',colors:['yellow','white'],meanings:['새로운 시작','희망','자존','응원'],seasons:['spring'],occasions:['newstart','graduation','cheer','birthday'],price:'low',scent:'보통',care:{water:'다른 꽃과 섞기 전 단독 물올림을 거치면 좋아요.',cut:'줄기 끝을 곧게 잘라주세요.',place:'서늘한 곳에서 관리하고 수액이 피부에 닿지 않게 주의하세요.',life:'대체로 4~8일'},pet:{cat:'danger',dog:'danger',note:'수선화는 특히 구근이 유해하며 꽃과 잎도 반려동물이 먹지 않도록 해야 합니다.',source:p+'daffodil'}},
    {id:'lavender',name:'라벤더',emoji:'💜',colors:['purple'],meanings:['평온','기다림','위로','행복'],seasons:['summer'],occasions:['cheer','thanks','birthday','apology'],price:'mid',scent:'강함',care:{water:'절화는 적은 물을 자주 교체하고 드라이용은 거꾸로 매달아 말릴 수 있어요.',cut:'줄기 끝을 사선으로 잘라주세요.',place:'향에 민감하다면 침실을 피하고 환기가 되는 곳에 두세요.',life:'절화 5~10일'},pet:{cat:'caution',dog:'caution',note:'섭취는 위장 불편을 유발할 수 있으며 에센셜오일은 더 농축되어 특히 주의하세요.',source:p+'lavender'}}
  ];
  const moods={joy:{label:'기분 좋음',emoji:'😊',plant:'해바라기',color:'노랑과 오렌지',music:'밝은 어쿠스틱 팝',message:'좋은 에너지를 너무 빨리 써버리지 말고 오늘의 기쁨을 한 문장으로 남겨보세요.',action:'고마운 사람 한 명에게 짧은 메시지를 보내기'},tired:{label:'지침',emoji:'😮‍💨',plant:'라벤더',color:'연보라와 회색',music:'느린 피아노와 빗소리',message:'지금 필요한 건 더 열심히가 아니라 회복할 틈일 수 있어요.',action:'물 한 잔을 마시고 5분 동안 화면에서 눈 떼기'},anxious:{label:'불안함',emoji:'😟',plant:'리시안셔스',color:'아이보리와 연두',music:'잔잔한 앰비언트',message:'불안은 아직 일어나지 않은 일을 미리 견디느라 생기기도 해요.',action:'걱정되는 일을 지금 할 수 있음과 나중에 할 일로 나누기'},lonely:{label:'외로움',emoji:'🥲',plant:'프리지아',color:'노랑과 크림',music:'따뜻한 보컬 재즈',message:'외로운 마음은 연결을 원한다는 신호예요. 거창한 대화가 아니어도 괜찮아요.',action:'부담 없는 안부 메시지 한 줄 보내기'},excited:{label:'설렘',emoji:'🥰',plant:'튤립',color:'분홍과 코랄',music:'경쾌한 시티팝',message:'설렘은 앞으로 나아갈 힘이 됩니다.',action:'오늘 기대되는 일을 메모에 한 줄 적기'},empty:{label:'무기력함',emoji:'😶',plant:'거베라',color:'살구와 연노랑',music:'느린 로파이',message:'아무것도 하기 싫은 날에는 아주 작은 완료가 마음을 다시 움직여요.',action:'2분 안에 끝나는 일 하나만 처리하기'},frustrated:{label:'답답함',emoji:'😣',plant:'수국',color:'파랑과 보라',music:'차분한 인스트루멘털',message:'답답함은 말로 정리되지 않은 감정이 쌓였다는 신호일 수 있어요.',action:'싫은 것, 원하는 것, 필요한 것을 한 줄씩 적기'},calm:{label:'평온함',emoji:'😌',plant:'호접란',color:'흰색과 연초록',music:'자연음과 미니멀 클래식',message:'평온한 순간은 그냥 지나치기보다 몸이 기억하도록 천천히 느껴보세요.',action:'창밖이나 가까운 식물을 1분 동안 바라보기'}};
  const birthFlowers={1:{flowers:['카네이션','스노드롭'],meaning:'사랑과 희망',trait:'차분하게 시작을 만드는 사람',colors:['white','pink']},2:{flowers:['제비꽃','아이리스'],meaning:'성실과 믿음',trait:'작은 약속을 오래 지키는 사람',colors:['purple','blue']},3:{flowers:['수선화'],meaning:'새로운 시작과 희망',trait:'변화를 두려워하지 않는 사람',colors:['yellow','white']},4:{flowers:['데이지','스위트피'],meaning:'순수와 기쁨',trait:'주변에 밝은 온도를 더하는 사람',colors:['white','pink']},5:{flowers:['은방울꽃','산사나무꽃'],meaning:'행복의 귀환',trait:'다정함을 행동으로 보여주는 사람',colors:['white','green']},6:{flowers:['장미','인동초'],meaning:'사랑과 감사',trait:'마음을 깊게 표현하는 사람',colors:['red','pink']},7:{flowers:['수련','델피니움'],meaning:'평온과 열린 마음',trait:'감정의 깊이를 아는 사람',colors:['blue','purple']},8:{flowers:['글라디올러스','양귀비'],meaning:'강인함과 상상력',trait:'자신의 색을 선명하게 지키는 사람',colors:['red','orange']},9:{flowers:['아스터','나팔꽃'],meaning:'지혜와 애정',trait:'사람과 상황을 섬세하게 읽는 사람',colors:['purple','pink']},10:{flowers:['메리골드','코스모스'],meaning:'따뜻함과 조화',trait:'어떤 자리에서도 균형을 찾는 사람',colors:['orange','yellow']},11:{flowers:['국화'],meaning:'성실과 존경',trait:'꾸준함으로 신뢰를 만드는 사람',colors:['yellow','white']},12:{flowers:['포인세티아','홀리'],meaning:'축복과 기쁨',trait:'한 해의 끝에 온기를 남기는 사람',colors:['red','green']}};
  const colorMeta={red:{label:'빨강',hex:'#c9534f',mood:'강렬하고 솔직한 사랑'},pink:{label:'분홍',hex:'#e9a3ad',mood:'다정하고 부드러운 애정'},orange:{label:'주황',hex:'#ef9a55',mood:'활력과 즐거운 응원'},yellow:{label:'노랑',hex:'#e2bd47',mood:'밝은 희망과 우정'},white:{label:'흰색',hex:'#f7f4ea',mood:'깨끗함과 담백한 진심'},purple:{label:'보라',hex:'#8c73aa',mood:'우아함과 깊은 마음'},blue:{label:'파랑',hex:'#6f99bb',mood:'평온과 신뢰'},green:{label:'초록',hex:'#789b6b',mood:'회복과 자연스러운 안정'}};
  const relationshipLabels={lover:'연인',friend:'친구',parents:'부모님',teacher:'선생님',coworker:'직장 동료',family:'가족',self:'나 자신'};
  const occasionLabels={birthday:'생일',anniversary:'기념일',confession:'고백',apology:'사과',thanks:'감사',graduation:'졸업·입학',newstart:'취업·이직·새출발',cheer:'응원·위로',parents:'부모님 선물',teacher:'스승의날',wedding:'결혼',opening:'개업·승진',memorial:'추모'};
  const styleLabels={warm:'따뜻하고 다정하게',bright:'밝고 생기 있게',elegant:'차분하고 우아하게',natural:'자연스럽고 편안하게',romantic:'로맨틱하고 풍성하게',minimal:'담백하고 미니멀하게'};
  window.EmoSeedToolsData={flowers,moods,birthFlowers,colorMeta,relationshipLabels,occasionLabels,styleLabels};
})();
