(() => {
  const data=window.EmoSeedToolsData;if(!data)return;
  const{flowers,moods,birthFlowers,colorMeta,relationshipLabels,occasionLabels,styleLabels}=data;
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],app=()=>window.EmoSeedApp||{};
  const statusLabels={safe:['비독성으로 분류','safe'],caution:['주의가 필요함','caution'],danger:['접근 금지 권장','danger']};
  const escapeHTML=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const formatDate=v=>{const d=v instanceof Date?v:new Date(v);return Number.isNaN(d.getTime())?'':`${d.getFullYear()}.${String(d.getMonth()+1).padStart(2,'0')}.${String(d.getDate()).padStart(2,'0')}`};
  const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const getStorage=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch(_){return f}},setStorage=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
  const toast=m=>app().toast?app().toast(m):console.info(m),copyText=async(t,m='복사했습니다.')=>app().copyText?app().copyText(t,m):navigator.clipboard.writeText(t),track=(n,d={})=>app().track?.(n,d);
  function openTool(key,updateHash=true){const safe=$(`[data-tool-panel="${CSS.escape(key)}"]`)?key:'mood';$$('[data-tool-panel]').forEach(p=>p.hidden=p.dataset.toolPanel!==safe);$$('[data-tool-switch]').forEach(b=>b.setAttribute('aria-current',b.dataset.toolSwitch===safe?'true':'false'));if(updateHash)history.replaceState(null,'',`#${safe}`);const panel=$(`[data-tool-panel="${CSS.escape(safe)}"]`);if(panel&&updateHash)requestAnimationFrame(()=>panel.scrollIntoView({behavior:'smooth',block:'start'}));track('free_tool_open',{tool:safe})}
  function initNavigation(){$$('[data-open-tool]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openTool(a.dataset.openTool)}));$$('[data-tool-switch]').forEach(b=>b.addEventListener('click',()=>openTool(b.dataset.toolSwitch)));openTool(location.hash.replace('#','')||'mood',false);addEventListener('hashchange',()=>openTool(location.hash.replace('#','')||'mood',false))}
  const actionButtons=(target,image='')=>`<div class="result-actions"><button type="button" data-copy-target="${target}">내용 복사</button>${image?`<button type="button" data-image-action="${image}">이미지 저장</button>`:''}</div>`;
  function initGlobalActions(){document.addEventListener('click',e=>{const c=e.target.closest('[data-copy-target]');if(c){const t=$(c.dataset.copyTarget);if(t)copyText(t.innerText.trim(),'내용을 복사했어요.')}const s=e.target.closest('[data-open-source]');if(s)open(s.dataset.openSource,'_blank','noopener');const i=e.target.closest('[data-image-action]');if(i){if(i.dataset.imageAction==='mood')saveMoodImage();if(i.dataset.imageAction==='gift')saveGiftImage();if(i.dataset.imageAction==='birth')saveBirthImage()}})}
  function initMood(){const target=$('#moodChoices');target.innerHTML=Object.entries(moods).map(([k,m])=>`<button class="mood-choice" type="button" data-mood="${k}" aria-pressed="false"><span>${m.emoji}</span><small>${m.label}</small></button>`).join('');target.addEventListener('click',e=>{const b=e.target.closest('[data-mood]');if(b)selectMood(b.dataset.mood)});$('#clearMoodHistory')?.addEventListener('click',()=>{setStorage('emoseed-mood-history',[]);renderMoodHistory();toast('감정 기록을 지웠어요.')});renderMoodHistory()}
  function selectMood(key){const m=moods[key];if(!m)return;$$('[data-mood]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mood===key?'true':'false'));const h=getStorage('emoseed-mood-history',[]).filter(x=>x.date!==todayKey());h.push({date:todayKey(),key});setStorage('emoseed-mood-history',h.slice(-30));setStorage('emoseed-last-mood',{date:todayKey(),key});const r=$('#moodResult');r.classList.add('has-content');r.innerHTML=`<div class="result-topline"><div><p class="result-kicker">TODAY'S MOOD PLANT</p><h3>${m.emoji} 오늘의 식물은 ${m.plant}</h3></div>${actionButtons('#moodCopyText','mood')}</div><p class="result-summary">${m.message}</p><div class="result-chip-row"><span class="result-chip">추천 색상 · ${m.color}</span><span class="result-chip">음악 분위기 · ${m.music}</span></div><div class="generated-copy" id="moodCopyText">오늘의 감정: ${m.label}\n오늘의 식물: ${m.plant}\n지금 해볼 작은 행동: ${m.action}\n\n${m.message}</div>`;renderMoodHistory();track('mood_checkin_complete',{mood:key})}
  function renderMoodHistory(){const t=$('#moodHistory'),h=getStorage('emoseed-mood-history',[]),map=new Map(h.map(x=>[x.date,x.key])),days=[];for(let o=6;o>=0;o--){const d=new Date();d.setDate(d.getDate()-o);const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;days.push({d,m:moods[map.get(k)]})}t.innerHTML=days.map(({d,m})=>`<div class="mood-day"><span>${d.getMonth()+1}/${d.getDate()}</span><strong>${m?.emoji||'·'}</strong><small>${m?.label||'기록 없음'}</small></div>`).join('');const last=getStorage('emoseed-last-mood',null);if(last?.date===todayKey()&&moods[last.key]&&!$('#moodResult')?.classList.contains('has-content'))selectMood(last.key)}
  function saveMoodImage(){const last=getStorage('emoseed-last-mood',null),m=last&&moods[last.key];if(!m||!app().downloadResultImage)return toast('먼저 감정을 선택해주세요.');app().downloadResultImage({kicker:'TODAY MOOD',title:`오늘의 식물은 ${m.plant}`,subtitle:`지금의 마음 · ${m.label}`,keywords:[m.color,m.music,'무료 감정 체크'],message:m.message,quote:m.action,filename:`emoseed-mood-${todayKey()}.png`})}
  const occasionMeaning={birthday:['행복','축하','사랑'],anniversary:['사랑','영원한 사랑','변치 않는 사랑'],confession:['사랑','고백','매력'],apology:['진심','이해','감사'],thanks:['감사','존경'],graduation:['응원','새로운 시작','희망'],newstart:['새로운 시작','응원','희망'],cheer:['응원','위로','희망','평온'],parents:['감사','존경','사랑'],teacher:['감사','존경'],wedding:['축복','행복','사랑'],opening:['축하','행복','희망'],memorial:['존경','평온','위로']};
  function flowerScore(f,v){let s=0;(occasionMeaning[v.occasion]||[]).forEach(m=>{if(f.meanings.includes(m))s+=4});if(v.color!=='any'&&f.colors.includes(v.color))s+=5;if(v.season!=='any'&&f.seasons.includes(v.season))s+=3;if(v.style==='bright'&&f.colors.some(c=>['yellow','orange','pink'].includes(c)))s+=2;if(v.style==='elegant'&&f.colors.some(c=>['white','purple','green'].includes(c)))s+=2;if(v.style==='romantic'&&f.meanings.some(m=>['사랑','영원한 사랑','매력'].includes(m)))s+=2;const b=Number(v.budget);if(b<=30000&&f.price==='low')s+=3;if(b>=50000&&f.price==='mid')s+=2;if(b>=100000&&f.price==='high')s+=4;if(v.pet!=='none'){if(f.pet[v.pet]==='safe')s+=5;if(f.pet[v.pet]==='danger')s-=100;if(f.pet[v.pet]==='caution')s-=5}return s}
  function makeCardMessage(r,o){const occasion=occasionLabels[o]||'오늘';return({lover:`함께하는 시간이 늘 고마워. ${occasion}을 진심으로 축하하고, 오늘도 많이 사랑해.`,parents:`늘 든든하게 곁을 지켜주셔서 감사합니다. ${occasion}을 진심으로 축하드려요.`,friend:`네가 있어서 평범한 날도 더 즐거워. ${occasion}을 진심으로 축하해!`,teacher:'따뜻한 가르침과 응원에 늘 감사드립니다. 작은 꽃에 감사한 마음을 담았습니다.',coworker:`${occasion}을 진심으로 축하드립니다. 앞으로의 날들도 좋은 일로 가득하시길 바랍니다.`,family:`늘 내 편이 되어줘서 고마워. ${occasion}을 함께 축하할 수 있어 행복해.`,self:'지금까지 잘 버텨온 나에게. 오늘만큼은 내 마음을 가장 먼저 돌봐주자.'}[r]||`${occasion}의 마음을 이 꽃에 담았습니다.`)}
  function initGift(){$('#giftForm')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));let selected=flowers.map(f=>({f,s:flowerScore(f,v)})).filter(x=>x.s>-50).sort((a,b)=>b.s-a.s).slice(0,3).map(x=>x.f);if(!selected.length)selected=flowers.filter(f=>v.pet==='none'||f.pet[v.pet]==='safe').slice(0,3);const palette=v.color!=='any'?[v.color,selected.flatMap(f=>f.colors).find(c=>c!==v.color)||'white']:[...new Set(selected.flatMap(f=>f.colors))].slice(0,3);const paletteText=palette.map(c=>colorMeta[c]?.label||c).join(' · '),rel=relationshipLabels[v.relationship],occ=occasionLabels[v.occasion],style=styleLabels[v.style],pet=v.pet==='none'?'':` ${v.pet==='cat'?'고양이':'강아지'}와 함께 사는 공간이므로 반려동물 안전성이 확인된 꽃 위주로 구성해주세요.`;const orderText=`${rel} ${occ} 선물용 꽃다발을 주문하고 싶습니다. 예산은 ${Number(v.budget).toLocaleString('ko-KR')}원 정도이며, ${style} 구성해주세요. 색상은 ${paletteText} 중심을 원합니다.${pet} 추천 꽃은 ${selected.map(f=>f.name).join(', ')}입니다. 가능한 꽃과 수령 일정 상담 부탁드립니다.`,cardText=makeCardMessage(v.relationship,v.occasion),r=$('#giftResult');r.classList.add('has-content');r.innerHTML=`<div class="result-topline"><div><p class="result-kicker">FREE BOUQUET PLAN</p><h3>${rel}을 위한 ${occ} 꽃다발</h3></div>${actionButtons('#giftCopyText','gift')}</div><p class="result-summary">${style} 표현하면서 ${paletteText} 색감으로 정리한 구성입니다. 계절과 재고에 따라 비슷한 꽃으로 대체할 수 있어요.</p><div class="result-chip-row">${selected.map(f=>`<span class="result-chip">${f.emoji} ${f.name}</span>`).join('')}<span class="result-chip">🎨 ${paletteText}</span><span class="result-chip">💰 ${Number(v.budget).toLocaleString('ko-KR')}원대</span></div><div class="result-grid"><section class="result-section"><h4>추천 구성</h4><p>${selected.map(f=>`${f.name}(${f.meanings.slice(0,2).join('·')})`).join(' + ')}</p></section><section class="result-section"><h4>카드 메시지</h4><p>${escapeHTML(cardText)}</p></section><section class="result-section"><h4>안전·대체 안내</h4><p>${v.pet==='none'?'향 민감도와 반려동물 유무를 꽃집에 함께 알려주세요.':'위험 등급 꽃은 추천에서 제외했습니다. 정확한 품종은 꽃집과 다시 확인하세요.'}</p></section></div><div class="generated-copy" id="giftCopyText">${escapeHTML(orderText)}\n\n카드 문구:\n${escapeHTML(cardText)}</div>`;setStorage('emoseed-last-gift',{values:v,selected:selected.map(f=>f.id),orderText,cardText,paletteText});track('gift_recommendation_complete',{relationship:v.relationship,occasion:v.occasion,budget:v.budget})})}
  function saveGiftImage(){const s=getStorage('emoseed-last-gift',null);if(!s||!app().downloadResultImage)return toast('먼저 꽃 선물 추천을 만들어주세요.');const chosen=s.selected.map(id=>flowers.find(f=>f.id===id)).filter(Boolean);app().downloadResultImage({kicker:'FREE BOUQUET PLAN',title:`${relationshipLabels[s.values.relationship]}을 위한 ${occasionLabels[s.values.occasion]} 꽃다발`,subtitle:chosen.map(f=>`${f.emoji} ${f.name}`).join(' · '),keywords:[s.paletteText,`${Number(s.values.budget).toLocaleString('ko-KR')}원대`,styleLabels[s.values.style]],message:s.orderText,quote:s.cardText,filename:'emoseed-bouquet-plan.png'})}
  function initOrder(){const date=$('#orderForm input[name="date"]');if(date){const d=new Date();d.setDate(d.getDate()+1);date.value=d.toISOString().slice(0,10)}$('#orderForm')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)),text=`안녕하세요. 꽃다발 주문 문의드립니다.\n\n- 선물 대상: ${v.target}\n- 기념일/상황: ${v.occasion}\n- 예산: ${v.budget}\n- 원하는 색상: ${v.color}\n- 원하는 분위기: ${v.style}\n- 수령 방식: ${v.delivery}\n- 희망 날짜: ${v.date?formatDate(v.date):'상담 후 결정'}\n- 피하고 싶은 요소: ${v.avoid||'특별히 없음'}\n${v.extra?`- 추가 요청: ${v.extra}`:''}\n\n해당 조건으로 가능한 꽃 구성과 정확한 수령 시간 안내 부탁드립니다. 감사합니다.`;const r=$('#orderResult');r.classList.add('has-content');r.innerHTML=`<div class="result-topline"><div><p class="result-kicker">ORDER REQUEST</p><h3>꽃집에 바로 보낼 주문 문구</h3></div>${actionButtons('#orderCopyText')}</div><div class="generated-copy" id="orderCopyText">${escapeHTML(text)}</div>`;track('flower_order_text_generated',{budget:v.budget})})}
  const baseMessages={birthday:['생일 진심으로 축하해. 오늘이 오래 기억될 좋은 하루였으면 좋겠어.','태어나줘서 고마워. 네가 웃는 일이 많은 한 해가 되길 바라.','오늘의 주인공에게, 가장 행복한 생일을!'],anniversary:['함께한 시간만큼 앞으로의 날들도 소중히 아낄게.','우리의 오늘을 축하해. 앞으로도 잘 부탁해.','같이여서 좋았고, 앞으로도 같이여서 좋을 것 같아.'],confession:['좋아해. 이 꽃을 핑계로 내 마음을 전하고 싶었어.','너와 더 많은 시간을 보내고 싶어.','내 마음은 오래전부터 너를 향하고 있었어.'],apology:['미안해. 변명보다 달라진 행동으로 보여줄게.','내 말과 행동으로 상처 줘서 정말 미안해.','네 마음을 먼저 생각하지 못했어. 미안해.'],thanks:['늘 고마워. 네 덕분에 많이 힘이 됐어.','작은 꽃에 큰 감사의 마음을 담았어.','함께해줘서 정말 고마워.'],graduation:['졸업을 축하해. 새로운 시작을 힘껏 응원할게.','지금까지의 노력에 박수를 보내. 앞으로도 잘할 거야.','한 챕터를 멋지게 마친 너를 축하해!'],newstart:['새로운 시작을 응원해. 네 속도로 잘 해낼 거야.','첫걸음을 내디딘 오늘을 축하해.','새로운 자리에서도 너답게 빛나길 바라.'],cheer:['지금도 충분히 잘하고 있어. 천천히 가도 괜찮아.','오늘은 버티는 것만으로도 잘한 하루야.','네 편이 여기 있다는 걸 잊지 마.']};
  const tonePrefix={warm:'다정한 마음을 담아, ',serious:'진심을 다해 전합니다. ',cute:'꽃보다 더 귀여운 너에게 🌷 ',formal:'깊은 마음을 담아, ',natural:'평소에 말 못 했지만, ',simple:''};
  function initMessage(){$('#messageForm')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)),list=baseMessages[v.occasion]||baseMessages.thanks,name=v.name.trim(),prefix=tonePrefix[v.tone]||'',msgs=list.map(t=>`${name?name+', ':''}${prefix}${t}`),r=$('#messageResult');r.classList.add('has-content');r.innerHTML=`<div class="result-topline"><div><p class="result-kicker">CARD MESSAGE</p><h3>${occasionLabels[v.occasion]||'마음'}을 담은 문구 3개</h3></div></div><div class="result-grid">${msgs.map((t,i)=>`<section class="result-section"><h4>문구 ${i+1}</h4><p id="cardMessage${i}">${escapeHTML(t)}</p><button class="copy-mini" type="button" data-copy-target="#cardMessage${i}">이 문구 복사</button></section>`).join('')}</div>`;track('card_message_generated',{occasion:v.occasion,tone:v.tone})})}
  function flowerCard(f){return `<article class="flower-mini-card"><div class="flower-emoji">${f.emoji}</div><h3>${f.name}</h3><p>${f.meanings.join(' · ')}</p><div class="result-chip-row">${f.colors.slice(0,3).map(c=>`<span class="result-chip">${colorMeta[c]?.label||c}</span>`).join('')}</div></article>`}
  function initMeaning(){const arr=[...new Set(flowers.flatMap(f=>f.meanings))].sort((a,b)=>a.localeCompare(b,'ko')),chips=$('#meaningChips');chips.innerHTML=arr.map(m=>`<button type="button" data-meaning="${m}" aria-pressed="false">${m}</button>`).join('');chips.addEventListener('click',e=>{const b=e.target.closest('[data-meaning]');if(!b)return;$('#meaningInput').value=b.dataset.meaning;$$('[data-meaning]').forEach(x=>x.setAttribute('aria-pressed',x===b?'true':'false'));renderMeaning(b.dataset.meaning)});$('#meaningInput')?.addEventListener('input',e=>renderMeaning(e.target.value));renderMeaning('감사')}
  function renderMeaning(q){const n=q.trim(),m=flowers.filter(f=>!n||f.meanings.some(x=>x.includes(n)||n.includes(x))),t=$('#meaningResult');t.innerHTML=m.length?m.map(flowerCard).join(''):'<div class="tool-result empty-result" style="grid-column:1/-1"><p>해당 의미와 가까운 꽃을 찾지 못했어요.</p></div>'}
  function initColor(){const p=$('#colorPicker');p.innerHTML=Object.entries(colorMeta).map(([k,c])=>`<button class="color-choice" type="button" data-color="${k}" aria-pressed="false"><span style="background:${c.hex}"></span>${c.label}</button>`).join('');p.addEventListener('click',e=>{const b=e.target.closest('[data-color]');if(!b)return;$$('[data-color]').forEach(x=>x.setAttribute('aria-pressed',x===b?'true':'false'));renderColor(b.dataset.color)})}
  function renderColor(k){const m=colorMeta[k],matches=flowers.filter(f=>f.colors.includes(k)).slice(0,6),comp={red:['pink','white'],pink:['white','green'],orange:['yellow','green'],yellow:['white','orange'],white:['green','pink'],purple:['white','pink'],blue:['white','purple'],green:['white','yellow']}[k]||['white'],r=$('#colorResult');r.classList.add('has-content');r.innerHTML=`<div class="result-topline"><div><p class="result-kicker">COLOR FLOWER GUIDE</p><h3>${m.label} 꽃다발 · ${m.mood}</h3></div></div><p class="result-summary">${comp.map(x=>colorMeta[x].label).join('·')}을 함께 쓰면 더 안정적인 조합이 됩니다.</p><div class="flower-result-grid">${matches.map(flowerCard).join('')}</div>`;track('color_flower_view',{color:k})}
  function fillFlowerSelect(s){if(s)s.innerHTML=flowers.map(f=>`<option value="${f.id}">${f.emoji} ${f.name}</option>`).join('')}
  function initPet(){fillFlowerSelect($('#petFlowerSelect'));$('#petForm')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));renderPet(v.flower,v.pet)})}
  function renderPet(id,pet){const f=flowers.find(x=>x.id===id);if(!f)return;const st=f.pet[pet]||'caution',[label,cl]=statusLabels[st],petName=pet==='cat'?'고양이':'강아지',alts=flowers.filter(x=>x.pet[pet]==='safe'&&x.id!==f.id).slice(0,3),r=$('#petResult');r.classList.add('has-content');r.innerHTML=`<div class="result-topline"><div><p class="result-kicker">PET FLOWER SAFETY</p><h3>${f.emoji} ${f.name} · ${petName}</h3></div><div class="result-actions"><button type="button" data-open-source="${f.pet.source}">출처 확인</button></div></div><span class="safety-status ${cl}">${st==='safe'?'✓':st==='danger'?'!':'△'} ${label}</span><p class="result-summary">${f.pet.note}</p><div class="result-grid"><section class="result-section"><h4>안전한 대체 후보</h4><p>${alts.map(x=>`${x.emoji} ${x.name}`).join(' · ')||'꽃집에 반려동물 안전 꽃을 문의하세요.'}</p></section><section class="result-section"><h4>공통 관리</h4><p>꽃과 잎, 포장재, 꽃병 물을 반려동물이 핥거나 먹지 않도록 분리하세요.</p></section><section class="result-section"><h4>노출이 의심되면</h4><p>꽃 이름과 노출 시간, 증상을 기록해 즉시 동물병원에 문의하세요.</p></section></div>`;track('pet_flower_safety_checked',{flower:f.id,pet,status:st})}
  function initCare(){fillFlowerSelect($('#careFlowerSelect'));const d=$('#careReceived');if(d)d.value=new Date().toISOString().slice(0,10);$('#careForm')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));renderCare(v.flower,v.received)});document.addEventListener('click',e=>{const b=e.target.closest('[data-care-complete]');if(!b)return;setStorage(`emoseed-care-${b.dataset.careComplete}`,{lastWater:todayKey(),received:b.dataset.received});renderCare(b.dataset.careComplete,b.dataset.received);toast('오늘 물 교체 기록을 저장했어요.')})}
  function renderCare(id,received){const f=flowers.find(x=>x.id===id);if(!f)return;const saved=getStorage(`emoseed-care-${id}`,{}),last=saved.lastWater?new Date(saved.lastWater):null,next=last?new Date(last):new Date();next.setDate(next.getDate()+(f.id==='gerbera'||f.id==='ranunculus'?1:2));const r=$('#careResult');r.classList.add('has-content');r.innerHTML=`<div class="result-topline"><div><p class="result-kicker">FLOWER CARE</p><h3>${f.emoji} ${f.name} 관리 일정</h3></div><div class="result-actions"><button type="button" data-care-complete="${f.id}" data-received="${escapeHTML(received)}">오늘 물 갈기 완료</button></div></div><div class="result-chip-row"><span class="result-chip">받은 날 · ${formatDate(received)}</span><span class="result-chip">예상 감상 기간 · ${f.care.life}</span><span class="result-chip">다음 물 교체 · ${formatDate(next)}</span></div><div class="care-checklist"><div class="care-item"><i>💧</i><div><strong>물 관리</strong><p>${f.care.water}</p></div></div><div class="care-item"><i>✂️</i><div><strong>줄기 정리</strong><p>${f.care.cut}</p></div></div><div class="care-item"><i>🌤️</i><div><strong>두는 장소</strong><p>${f.care.place}</p></div></div><div class="care-item"><i>🧼</i><div><strong>공통 관리</strong><p>깨끗한 꽃병을 사용하고 물에 잠기는 잎을 제거하세요. 익은 과일과 강한 바람에서 떨어뜨려 놓는 것이 좋습니다.</p></div></div></div><p class="result-summary">${last?`마지막 물 교체 기록: ${formatDate(last)}`:'아직 물 교체 기록이 없습니다.'}</p>`;track('flower_care_view',{flower:f.id})}
  function initBirth(){$('#birthForm')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)),d=new Date(`${v.birthday}T12:00:00`);if(Number.isNaN(d.getTime()))return toast('생일을 입력해주세요.');renderBirth(d,v.relationship)})}
  function renderBirth(d,rel){const info=birthFlowers[d.getMonth()+1],who=relationshipLabels[rel]||'소중한 사람',card=rel==='self'?`지금까지 잘 자라온 나에게. ${info.meaning}의 마음을 담아 오늘의 나를 축하해.`:`${who}의 생일을 진심으로 축하해. ${info.flowers.join('과 ')}처럼 ${info.meaning}이 가득한 한 해가 되길 바라.`,colors=info.colors.map(k=>colorMeta[k]?.label||k).join(' · '),r=$('#birthResult');r.classList.add('has-content');r.innerHTML=`<div class="result-topline"><div><p class="result-kicker">${d.getMonth()+1} MONTH BIRTH FLOWER</p><h3>🎂 ${info.flowers.join(' · ')}</h3></div>${actionButtons('#birthCopyText','birth')}</div><p class="result-summary">${d.getMonth()+1}월의 탄생화는 ${info.flowers.join(', ')}이며, ${info.meaning}의 의미를 담고 있습니다.</p><div class="result-grid"><section class="result-section"><h4>탄생화 성향</h4><p>${info.trait}</p></section><section class="result-section"><h4>추천 꽃다발</h4><p>${colors} 색상에 리시안셔스나 안개꽃을 더해 부드럽게 구성해보세요.</p></section><section class="result-section"><h4>카드 문구</h4><p>${escapeHTML(card)}</p></section></div><div class="generated-copy" id="birthCopyText">${d.getMonth()+1}월 탄생화: ${info.flowers.join(', ')}\n꽃말: ${info.meaning}\n성향: ${info.trait}\n추천 색상: ${colors}\n\n${escapeHTML(card)}</div>`;setStorage('emoseed-last-birth',{month:d.getMonth()+1,relationship:rel,card});track('birth_flower_view',{month:d.getMonth()+1})}
  function saveBirthImage(){const s=getStorage('emoseed-last-birth',null);if(!s||!app().downloadResultImage)return toast('먼저 탄생화를 확인해주세요.');const i=birthFlowers[s.month];app().downloadResultImage({kicker:`${s.month} MONTH BIRTH FLOWER`,title:`${s.month}월의 탄생화`,subtitle:i.flowers.join(' · '),keywords:[i.meaning,i.trait],message:`추천 색상: ${i.colors.map(k=>colorMeta[k]?.label||k).join(' · ')}`,quote:s.card,filename:`emoseed-birth-flower-${s.month}.png`})}
  const wrapColors={cream:'#eee5d0',pink:'#efd7dc',green:'#cfdcc9',gray:'#d8d4cf',navy:'#596778',kraft:'#c9a77c'};
  function initBouquet(){fillFlowerSelect($('#bouquetMain'));fillFlowerSelect($('#bouquetSub'));$('#bouquetMain').value='rose';$('#bouquetSub').value='babybreath';$('#bouquetForm')?.addEventListener('input',updateBouquetPreview);$('#bouquetForm')?.addEventListener('submit',e=>{e.preventDefault();updateBouquetPreview();renderBouquetResult(Object.fromEntries(new FormData(e.currentTarget)))});updateBouquetPreview()}
  function bouquetEmojiPattern(main,sub,size){const count=size==='small'?3:size==='large'?7:5,line1=Array(Math.max(2,Math.ceil(count/2))).fill(main.emoji).join(' '),items=[];for(let i=0;i<count;i++)items.push(i%2?sub.emoji:main.emoji);return `${line1}<br>${items.join(' ')}${size==='large'?`<br>${sub.emoji} ${main.emoji} ${sub.emoji} ${main.emoji} ${sub.emoji}`:''}`}
  function updateBouquetPreview(){const f=$('#bouquetForm');if(!f)return;const v=Object.fromEntries(new FormData(f)),main=flowers.find(x=>x.id===v.main)||flowers[0],sub=flowers.find(x=>x.id===v.sub)||flowers[1];$('#bouquetFlowers').innerHTML=bouquetEmojiPattern(main,sub,v.size);$('#bouquetPreview').style.setProperty('--wrap-color',wrapColors[v.wrap]||wrapColors.cream)}
  function renderBouquetResult(v){const main=flowers.find(x=>x.id===v.main),sub=flowers.find(x=>x.id===v.sub),sizes={small:'미니 꽃다발',medium:'기본 꽃다발',large:'풍성한 꽃다발'},styles={natural:'자연스럽게',round:'둥글고 단정하게',airy:'여백감 있게',romantic:'로맨틱하게'},wraps={cream:'크림',pink:'연분홍',green:'세이지 그린',gray:'웜그레이',navy:'네이비',kraft:'크라프트'},budget=v.size==='small'?'3만원 전후':v.size==='large'?'7만~10만원 이상':'5만원 전후',text=`메인 꽃: ${main.name}\n서브 꽃: ${sub.name}\n크기: ${sizes[v.size]}\n구성 느낌: ${styles[v.style]}\n포장: ${wraps[v.wrap]}\n예상 예산: ${budget}\n\n${main.name}을 중심으로 ${sub.name}을 사이사이에 배치하고, ${wraps[v.wrap]} 포장지로 ${styles[v.style]} 구성해주세요. 실제 꽃 수량과 가격은 계절 및 재고에 따라 상담 부탁드립니다.`,r=$('#bouquetResult');r.classList.add('has-content');r.innerHTML=`<div class="result-topline"><div><p class="result-kicker">BOUQUET COMBINATION</p><h3>${main.emoji} ${main.name} × ${sub.emoji} ${sub.name}</h3></div>${actionButtons('#bouquetCopyText')}</div><div class="result-chip-row"><span class="result-chip">${sizes[v.size]}</span><span class="result-chip">${wraps[v.wrap]} 포장</span><span class="result-chip">${budget}</span></div><div class="generated-copy" id="bouquetCopyText">${escapeHTML(text)}</div>`;track('bouquet_simulation_complete',{main:main.id,sub:sub.id,size:v.size})}
  function init(){initNavigation();initGlobalActions();initMood();initGift();initOrder();initMessage();initMeaning();initColor();initPet();initCare();initBirth();initBouquet()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
